apiVersion: v1
kind: Service
metadata:
  name: pong-service
spec:
  selector:
    app: pong-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
spec:
  selector:
    matchLabels:
      app: pong-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong
          image: pong:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
