apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /persistent_volume/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-log-storage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: log-pv
  resources:
    requests:
      storage: 100Mi